<?php echo doctype('html5'); ?><html><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><title><?php echo $this->config->item('sitename'); ?> | <?php echo $title ?></title><meta content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no" name="viewport">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="application-name" content="MyLoanAdmin">
<meta name="apple-mobile-web-app-title" content="MyLoanAdmin">
<meta name="theme-color" content="#3c8dbc">
<meta name="msapplication-navbutton-color" content="#3c8dbc">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="msapplication-starturl" content="/">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="apple-touch-icon" sizes="57x57" href="<?= base_url(IMGPATH); ?>favicon/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="<?= base_url(IMGPATH); ?>favicon/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="<?= base_url(IMGPATH); ?>favicon/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="<?= base_url(IMGPATH); ?>favicon/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="<?= base_url(IMGPATH); ?>favicon/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="<?= base_url(IMGPATH); ?>favicon/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="<?= base_url(IMGPATH); ?>favicon/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="<?= base_url(IMGPATH); ?>favicon/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="<?= base_url(IMGPATH); ?>favicon/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="<?= base_url(IMGPATH); ?>favicon/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="<?= base_url(IMGPATH); ?>favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="<?= base_url(IMGPATH); ?>favicon/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="<?= base_url(IMGPATH); ?>favicon/favicon-16x16.png">
<link rel="manifest" href="<?=base_url(PUBLICPATH);?>manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="<?= base_url(IMGPATH); ?>favicon/ms-icon-144x144.png">
<meta name="theme-color" content="#3c8dbc">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"><style>body,html{height:100%}body{overflow-x:hidden;overflow-y:auto}.btn:focus,a:active,a:focus,a:hover{outline:0}body{font-family:'Source Sans Pro','Helvetica Neue',Helvetica,Arial,sans-serif;font-weight:400}a{color:#3c8dbc}a:active,a:focus,a:hover{text-decoration:none;color:#72afd2}.form-control{border-radius:0}.form-control{box-shadow:none;border-color:#d2d6de}.form-control:focus{border-color:#3c8dbc;box-shadow:none}.form-control:-ms-input-placeholder,.form-control::-moz-placeholder,.form-control::-webkit-input-placeholder{color:#bbb;opacity:1}.form-control:not(select){-webkit-appearance:none;-moz-appearance:none;appearance:none}.icheck>label{padding-left:0}.btn{border-radius:3px}.btn{-webkit-box-shadow:none;box-shadow:none;border:1px solid transparent}.btn.btn-flat{border-radius:0;-webkit-box-shadow:none;-moz-box-shadow:none;box-shadow:none;border-width:1px}.btn:active{-webkit-box-shadow:inset 0 3px 5px rgba(0,0,0,.125);-moz-box-shadow:inset 0 3px 5px rgba(0,0,0,.125);box-shadow:inset 0 3px 5px rgba(0,0,0,.125)}.btn-primary{background-color:#3c8dbc;border-color:#367fa9}.btn-primary:active,.btn-primary:hover{background-color:#367fa9}.login-logo a{color:#444}.login-logo{font-size:35px;text-align:center;margin-bottom:25px;font-weight:300}.login-logo b {color:#fff}.login-page{background:#607D8B}.login-box{width:360px;margin:2% auto}@media (max-width:768px){.login-box{width:90%;margin-top:20px}}.login-box-body{background:#fff;padding:20px;border-top:0;color:#666}.login-box-body .form-control-feedback{color:#777}.login-box-msg{margin:0;text-align:center;padding:0 20px 20px}@font-face{font-family:Ionicons;src:url(../fonts/ionicons.eot?v=2.0.0);src:url(../fonts/ionicons.eot?v=2.0.0#iefix) format("embedded-opentype"),url(../fonts/ionicons.ttf?v=2.0.0) format("truetype"),url(../fonts/ionicons.woff?v=2.0.0) format("woff"),url(../fonts/ionicons.svg?v=2.0.0#Ionicons) format("svg");font-weight:400;font-style:normal}</style><!--[if lt IE 9]><script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]--><link rel="stylesheet" crossorigin rel="preconnect" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic"></head><body class="hold-transition login-page"><div class="login-box"><div class="login-logo">
  <div class="logo">
    <img src="<?php echo base_url(IMGPATH); ?>favicon/apple-icon-180x180.png" alt="<?php echo $this->config->item('sitename'); ?>">
  </div>
  <a href="<?php echo base_url(); ?>"><b><?php echo $this->config->item('sitename'); ?></b></a></div><div class="login-box-body"><p class="login-box-msg">Ingresa tus datos para iniciar sesion</p><form action="<?php echo base_url('admin/login/validar/'); ?>" method="post"><div class="form-group has-feedback"><input name="username" class="form-control" placeholder="Usuario"> <span class="glyphicon glyphicon-user form-control-feedback"></span></div><div class="form-group has-feedback"><input type="password" name="password" class="form-control" placeholder="Contraseña"> <span class="glyphicon glyphicon-lock form-control-feedback"></span></div><?php if (isset($error)) : ?><p class="red-text"></p><div class="alert alert-danger alert-dismissible"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><h4><i class="icon fa fa-ban"></i> Error!</h4><?php echo $error; ?></div><?php endif ?><div class="row"><div class="col-xs-8"></div><div class="col-xs-4"><button type="submit" class="btn btn-primary btn-block btn-flat">Ingresar</button></div></div></form></div></div><script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script><script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script></body></html>